name: build 

on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      # The below should be in a requirements file maybe?
      - run: pip install pillow cairosvg
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-blogging-plugin
      - run: mkdocs gh-deploy --force